### ISSUE TITLE
mvnw does not have executable permissions

### ISSUE THREAD

**Issue by frederickfogerty** [kblincoe/QualOpt_SE701#57] opened 2018-03-07 00:27 UTC
Running `./mvnw` from a freshly cloned repository does not work (for me at least). I needed to run `chmod +x mvnw` to make this work.

The `x` permission should be added to `mvnw`. Alternatively, as @Nateeo mentioned [below](https://github.com/kblincoe/QualOpt_SE701/issues/57#issuecomment-370980353), the documentation could be changed `bash ./mvnw`

**Comment by frederickfogerty** [comment] 2018-03-07 00:27
@softeng-701

**Comment by Nateeo** [comment] 2018-03-07 00:36
yeah I had the same issue, an alternative is we could change the instructions to simply do `bash ./mvnw`

**Comment by TheGuardianWolf** [comment] 2018-03-07 03:51
This is probably related to the #51 issue I made, as soon as I changed the line ending it works, I didn't need the chmod +x.

**Comment by frederickfogerty** [comment] 2018-03-07 04:04
@TheGuardianWolf thanks for the investigation, I could not get it to work by changing the line endings (I have just tested this now).

**Comment by TheGuardianWolf** [comment] 2018-03-07 04:07
In that case, I propose we do both changes, I know the issue is fixed for me after I change gitattributes and reclone.

**Comment by softeng-701** [comment] 2018-03-08 21:22
@frederickfogerty specify the size please! Please do it in all your future requests!

**Comment by frederickfogerty** [comment] 2018-03-08 21:42
@softeng-701 will do. I think this is `very-small`

**Comment by softeng-701** [comment] 2018-03-13 03:47
@frederickfogerty Awesome! APPROVED!

**Comment by TheGuardianWolf** [comment] 2018-03-15 01:17
Has this issue been merged in yet? If not then my very large issue's pull is going to fix this as a side effect, so pull now before it's too late.

**Closed** 2018-03-21 09:52 UTC
Labels: very-small
